// Wortlisten: "Wort|Hinweis für Imposter|ähnliches Wort (Undercover-Modus)"
window.IMPOSTER_CATEGORIES = [
  { id: 'essen', name: 'Essen & Trinken', icon: '🍕', words:
    'Pizza|Italien|Flammkuchen;Döner|Imbiss|Dürüm;Sushi|Japan|Onigiri;Spaghetti|Nudeln|Lasagne;Pommes|Frittiert|Kroketten;Burger|Fast Food|Sandwich;Brezel|Bäckerei|Croissant;Schnitzel|Paniert|Cordon bleu;Kaffee|Morgens|Tee;Bier|Oktoberfest|Wein;Schokolade|Süß|Bonbon;Eis|Sommer|Frozen Joghurt;Kartoffelsalat|Grillparty|Nudelsalat;Currywurst|Ruhrpott|Bratwurst;Maultaschen|Schwaben|Ravioli;Spätzle|Schwaben|Nudeln;Pfannkuchen|Pfanne|Waffel;Banane|Gelb|Mango;Erdbeere|Rot|Himbeere;Popcorn|Kino|Chips;Honig|Biene|Marmelade;Käse|Milch|Butter;Ei|Frühstück|Omelett;Suppe|Löffel|Eintopf;Kuchen|Geburtstag|Torte;Tacos|Mexiko|Burrito;Apfelstrudel|Österreich|Apfelkuchen;Cola|Sprudel|Limonade;Müsli|Schüssel|Cornflakes;Knoblauch|Vampir|Zwiebel' },
  { id: 'tiere', name: 'Tiere', icon: '🦁', words:
    'Hund|Haustier|Wolf;Katze|Schnurren|Tiger;Elefant|Rüssel|Nashorn;Giraffe|Hals|Zebra;Pinguin|Eis|Papagei;Hai|Meer|Delfin;Löwe|König|Tiger;Biene|Honig|Wespe;Schlange|Giftig|Eidechse;Pferd|Reiten|Esel;Kuh|Bauernhof|Schaf;Eule|Nacht|Fledermaus;Krokodil|Zähne|Alligator;Affe|Banane|Gorilla;Hamster|Käfig|Meerschweinchen;Schnecke|Langsam|Schildkröte;Spinne|Netz|Ameise;Känguru|Australien|Koala;Frosch|Teich|Kröte;Adler|Fliegen|Falke;Maus|Käse|Ratte;Bär|Winterschlaf|Panda;Fuchs|Schlau|Wolf;Igel|Stacheln|Stachelschwein;Wal|Riesig|Hai;Huhn|Eier|Ente;Schmetterling|Raupe|Libelle;Kamel|Wüste|Lama;Oktopus|Arme|Qualle;Flamingo|Rosa|Storch' },
  { id: 'berufe', name: 'Berufe', icon: '👷', words:
    'Arzt|Krankenhaus|Krankenpfleger;Lehrer|Schule|Erzieher;Polizist|Uniform|Feuerwehrmann;Bäcker|Früh aufstehen|Konditor;Pilot|Flughafen|Flugbegleiter;Koch|Küche|Kellner;Friseur|Schere|Kosmetiker;Mechaniker|Werkstatt|Elektriker;Zahnarzt|Bohren|Arzt;Astronaut|Weltall|Pilot;Anwalt|Gericht|Richter;Bauer|Traktor|Gärtner;Programmierer|Computer|Hacker;Zauberer|Trick|Clown;Maler|Farbe|Künstler;Postbote|Briefe|Paketbote;Tierarzt|Tiere|Arzt;Fotograf|Kamera|Kameramann;Busfahrer|Haltestelle|Taxifahrer;Dachdecker|Höhe|Maurer;Metzger|Fleisch|Koch;Sänger|Bühne|Musiker;Fußballer|Stadion|Trainer;Schauspieler|Film|Sänger;Feuerwehrmann|Brand|Rettungssanitäter;Kassierer|Supermarkt|Verkäufer;CNC-Dreher|Maschine|Fräser;Detektiv|Rätsel|Polizist;Bibliothekar|Bücher|Buchhändler;Müllmann|Tonne|Straßenkehrer' },
  { id: 'orte', name: 'Orte', icon: '📍', words:
    'Strand|Sand|Schwimmbad;Krankenhaus|Kranke|Arztpraxis;Schule|Lernen|Universität;Kino|Film|Theater;Flughafen|Reisen|Bahnhof;Supermarkt|Einkaufen|Kiosk;Zoo|Tiere|Bauernhof;Friedhof|Ruhe|Kirche;Gefängnis|Zelle|Polizeiwache;Disco|Tanzen|Bar;Bibliothek|Bücher|Buchladen;Fitnessstudio|Hanteln|Sporthalle;Freizeitpark|Achterbahn|Jahrmarkt;Kirche|Glocken|Moschee;Bäckerei|Brötchen|Café;Tankstelle|Benzin|Autowaschanlage;Campingplatz|Zelt|Wohnmobil;Restaurant|Speisekarte|Imbiss;Museum|Ausstellung|Galerie;Hotel|Übernachten|Jugendherberge;U-Bahn|Untergrund|Straßenbahn;Spielplatz|Rutsche|Kindergarten;Bank|Geld|Post;Weltall|Sterne|Mond;Schloss|König|Burg;Wald|Bäume|Park;Baustelle|Kran|Werkstatt;Sauna|Heiß|Dampfbad;Kreuzfahrtschiff|Meer|Fähre;Stadion|Fans|Arena' },
  { id: 'sport', name: 'Sport', icon: '⚽', words:
    'Fußball|Tor|Handball;Basketball|Korb|Volleyball;Tennis|Schläger|Badminton;Schwimmen|Wasser|Tauchen;Boxen|Handschuhe|Kickboxen;Skifahren|Schnee|Snowboard;Golf|Loch|Minigolf;Radfahren|Pedale|Mountainbike;Joggen|Laufen|Marathon;Yoga|Matte|Pilates;Reiten|Pferd|Pony;Bowling|Kegel|Kegeln;Darts|Pfeile|Bogenschießen;Formel 1|Rennen|Kartfahren;Eishockey|Puck|Eiskunstlauf;Surfen|Welle|Windsurfen;Klettern|Wand|Bouldern;Tischtennis|Platte|Tennis;Schach|Figuren|Dame;Turnen|Reck|Akrobatik;Rudern|Boot|Kanu;Fechten|Degen|Kampfsport;Gewichtheben|Hantel|Bodybuilding;Skateboard|Rollen|Inliner;Angeln|Fisch|Jagen;Billard|Kugeln|Snooker;Ringen|Matte|Judo;Rugby|Ei|American Football' },
  { id: 'haushalt', name: 'Haushalt', icon: '🏠', words:
    'Kühlschrank|Kalt|Gefriertruhe;Waschmaschine|Wäsche|Trockner;Staubsauger|Saugen|Besen;Bett|Schlafen|Sofa;Toaster|Brot|Sandwichmaker;Mikrowelle|Aufwärmen|Backofen;Fernseher|Bildschirm|Radio;Spiegel|Reflexion|Fenster;Zahnbürste|Bad|Haarbürste;Kerze|Licht|Lampe;Teppich|Boden|Fußmatte;Kissen|Weich|Decke;Gabel|Besteck|Löffel;Topf|Kochen|Pfanne;Schlüssel|Tür|Schloss;Wecker|Morgens|Uhr;Föhn|Haare|Glätteisen;Regenschirm|Regen|Sonnenschirm;Bügeleisen|Falten|Dampfglätter;Mülleimer|Abfall|Papierkorb;Kaffeemaschine|Bohnen|Wasserkocher;Dusche|Wasser|Badewanne;Handtuch|Abtrocknen|Bademantel;Schere|Schneiden|Messer;Gießkanne|Pflanzen|Sprühflasche;Vorhang|Fenster|Jalousie;Kleiderschrank|Kleidung|Kommode;Klopapier|Toilette|Taschentuch;Fernbedienung|Knöpfe|Controller;Steckdose|Strom|Verlängerungskabel' },
  { id: 'laender', name: 'Länder & Städte', icon: '🌍', words:
    'Italien|Stiefel|Spanien;Japan|Sushi|China;Frankreich|Eiffelturm|Belgien;USA|Freiheitsstatue|Kanada;Ägypten|Pyramiden|Marokko;Australien|Kängurus|Neuseeland;Brasilien|Samba|Argentinien;Russland|Groß|Ukraine;Mexiko|Sombrero|Spanien;Schweiz|Berge|Österreich;Griechenland|Inseln|Türkei;Indien|Curry|Pakistan;Paris|Liebe|London;Berlin|Hauptstadt|Hamburg;New York|Wolkenkratzer|Chicago;Rom|Kolosseum|Athen;Venedig|Gondeln|Amsterdam;Mallorca|Party|Ibiza;London|Big Ben|Dublin;Dubai|Wüste|Katar;Las Vegas|Casino|Monaco;Hawaii|Vulkan|Bali;Norwegen|Fjorde|Schweden;Island|Geysire|Grönland;Thailand|Tempel|Vietnam;Holland|Tulpen|Dänemark;München|Oktoberfest|Stuttgart;Stuttgart|Autos|Karlsruhe;Hollywood|Film|Beverly Hills;Antarktis|Eis|Arktis' },
  { id: 'fahrzeuge', name: 'Fahrzeuge', icon: '🚗', words:
    'Auto|Straße|Motorrad;Fahrrad|Pedale|Roller;Flugzeug|Fliegen|Hubschrauber;Zug|Schienen|Straßenbahn;Schiff|Meer|Boot;Bus|Haltestelle|Reisebus;Traktor|Feld|Mähdrescher;Rakete|Weltall|Space Shuttle;U-Boot|Unterwasser|Schiff;Feuerwehrauto|Leiter|Krankenwagen;Taxi|Gelb|Uber;Lkw|Ladung|Transporter;Skateboard|Rollen|Longboard;Heißluftballon|Schweben|Zeppelin;Polizeiauto|Blaulicht|Krankenwagen;Gabelstapler|Lager|Hubwagen;Bagger|Baustelle|Radlader;Kutsche|Pferde|Schlitten;Wohnmobil|Urlaub|Wohnwagen;Jetski|Wasser|Motorboot;E-Scooter|Elektrisch|Segway;Seilbahn|Berg|Sessellift;Panzer|Militär|Jeep;Formel-1-Wagen|Rennstrecke|Kart;Monstertruck|Riesenreifen|Pick-up;Segelboot|Wind|Kanu;Müllauto|Tonnen|Kehrmaschine;Rikscha|Asien|Tuk-Tuk;Achterbahn|Kirmes|Geisterbahn;Fallschirm|Springen|Gleitschirm' },
  { id: 'kleidung', name: 'Kleidung', icon: '👕', words:
    'Jeans|Blau|Jogginghose;Socken|Füße|Strumpfhose;Mütze|Winter|Cap;Krawatte|Anzug|Fliege;Bikini|Strand|Badeanzug;Pyjama|Schlafen|Bademantel;Hoodie|Kapuze|Pullover;Turnschuhe|Sport|Sandalen;Gummistiefel|Regen|Stiefel;Brille|Augen|Sonnenbrille;Handschuhe|Hände|Fäustlinge;Schal|Hals|Halstuch;Kleid|Elegant|Rock;Gürtel|Hose|Hosenträger;Anzug|Hochzeit|Smoking;Unterhose|Drunter|Boxershorts;Lederjacke|Biker|Jeansjacke;Ring|Finger|Armband;Uhr|Handgelenk|Armband;Hut|Kopf|Mütze;Dirndl|Oktoberfest|Lederhose;Regenjacke|Wasserdicht|Windjacke;Hausschuhe|Zuhause|Socken;Rucksack|Schule|Handtasche;Perücke|Haare|Hut;Uniform|Beruf|Arbeitskleidung;Schürze|Kochen|Kittel;Flip-Flops|Sommer|Sandalen;Badehose|Schwimmen|Shorts;Kostüm|Fasching|Verkleidung' },
  { id: 'musik', name: 'Musik', icon: '🎸', words:
    'Gitarre|Saiten|Bass;Klavier|Tasten|Keyboard;Schlagzeug|Trommeln|Cajón;Geige|Bogen|Cello;Trompete|Blasen|Posaune;Flöte|Pusten|Klarinette;Mikrofon|Singen|Lautsprecher;Konzert|Bühne|Festival;Karaoke|Singen|Konzert;DJ|Platten|Produzent;Rap|Reime|Hip-Hop;Oper|Klassisch|Musical;Schlager|Mallorca|Volksmusik;Rock|Laut|Metal;Chor|Gruppe|Band;Kopfhörer|Ohren|Lautsprecher;Mundharmonika|Klein|Akkordeon;Harfe|Engel|Lyra;Ukulele|Hawaii|Gitarre;Saxophon|Jazz|Klarinette;Dudelsack|Schottland|Akkordeon;Taktstock|Dirigent|Metronom;Plattenspieler|Vinyl|Kassette;Radio|Sender|Podcast;Tanz|Bewegung|Ballett;Nationalhymne|Fußball|Volkslied;Weihnachtslied|Advent|Kinderlied;Triangel|Klingeln|Glockenspiel;Spotify|Streaming|Radio;Eurovision|Wettbewerb|Castingshow' },
  { id: 'natur', name: 'Natur & Wetter', icon: '🌋', words:
    'Vulkan|Lava|Berg;Regenbogen|Farben|Polarlicht;Gewitter|Blitz|Sturm;Schnee|Weiß|Hagel;Wüste|Sand|Steppe;Dschungel|Lianen|Wald;Wasserfall|Fallen|Fluss;Mond|Nacht|Sonne;Tornado|Wirbel|Hurrikan;Insel|Meer|Halbinsel;Höhle|Dunkel|Tunnel;Gletscher|Eis|Eisberg;Erdbeben|Wackeln|Tsunami;Nebel|Grau|Wolke;Sonnenuntergang|Abend|Sonnenaufgang;Rose|Dornen|Tulpe;Kaktus|Stacheln|Aloe Vera;Pilz|Wald|Moos;Sternschnuppe|Wunsch|Komet;See|Wasser|Teich;Strand|Muscheln|Küste;Baum|Holz|Busch;Sonnenblume|Gelb|Löwenzahn;Herbst|Blätter|Frühling;Hitzewelle|Heiß|Dürre;Korallenriff|Bunt|Aquarium;Lagerfeuer|Flammen|Kamin;Blitz|Donner|Funke;Eiszapfen|Spitz|Schneeflocke;Meteorit|Einschlag|Asteroid' },
  { id: 'freizeit', name: 'Freizeit & Hobbys', icon: '🎮', words:
    'Videospiele|Konsole|Brettspiele;Angeln|Geduld|Jagen;Kochen|Rezept|Backen;Lesen|Buch|Hörbuch;Zelten|Natur|Glamping;Grillen|Kohle|Kochen;Malen|Pinsel|Zeichnen;Tanzen|Musik|Ballett;Gärtnern|Erde|Rasenmähen;Fotografieren|Bilder|Filmen;Wandern|Berge|Spazieren;Puzzle|Teile|Lego;Stricken|Wolle|Häkeln;Shoppen|Einkaufen|Flohmarkt;Netflix|Serien|Kino;Poker|Karten|Roulette;Sauna|Schwitzen|Whirlpool;Escape Room|Rätsel|Krimidinner;Bowling|Kugel|Kegeln;Picknick|Decke|Grillen;Karaoke|Singen|Tanzen;Zaubern|Tricks|Jonglieren;Tauchen|Unterwasser|Schnorcheln;Fallschirmspringen|Flugzeug|Bungee;Modellbau|Kleben|Lego;Sammeln|Briefmarken|Münzen;Meditieren|Ruhe|Yoga;Festival|Zelte|Konzert;Kreuzworträtsel|Zeitung|Sudoku;Instagram|Fotos|TikTok' },
  { id: 'werkstatt', name: 'Werkstatt & Technik', icon: '🔧', words:
    'Hammer|Nagel|Schlägel;Schraubenzieher|Schraube|Akkuschrauber;Bohrmaschine|Loch|Fräse;Säge|Holz|Flex;Zange|Greifen|Schraubstock;Drehbank|Spindel|Fräsmaschine;Schweißgerät|Funken|Lötkolben;Messschieber|Messen|Mikrometer;Wasserwaage|Gerade|Zollstock;Schraubstock|Einspannen|Zwinge;Akku|Laden|Batterie;Kabel|Strom|Stecker;Roboter|Automatisch|Drohne;Smartphone|Apps|Tablet;Laptop|Tastatur|Computer;Drucker|Papier|Kopierer;WLAN|Internet|Bluetooth;3D-Drucker|Filament|Laser;Kompressor|Luft|Pumpe;Schleifpapier|Rau|Feile;Gewinde|Schraube|Mutter;Werkbank|Arbeitsfläche|Tisch;Leiter|Hoch|Gerüst;Taschenlampe|Licht|Stirnlampe;Kühlschmierstoff|Emulsion|Öl;Spannfutter|Backen|Spannzange;Lupe|Vergrößern|Mikroskop;Klebeband|Kleben|Sekundenkleber;Magnet|Anziehen|Kompass;Solaranlage|Sonne|Windrad' },
  { id: 'feste', name: 'Feste & Feiern', icon: '🎉', words:
    'Weihnachten|Geschenke|Nikolaus;Ostern|Eier|Pfingsten;Silvester|Feuerwerk|Neujahr;Geburtstag|Kerzen|Jubiläum;Hochzeit|Ringe|Verlobung;Halloween|Kürbis|Fasching;Fasching|Kostüm|Halloween;Oktoberfest|Bier|Weinfest;Junggesellenabschied|Party|Polterabend;Taufe|Baby|Kommunion;Abiball|Schule|Abschlussfeier;Weihnachtsmarkt|Glühwein|Jahrmarkt;Valentinstag|Liebe|Muttertag;Grillparty|Garten|Gartenfest;Einweihungsparty|Neue Wohnung|Richtfest;Babyparty|Schwanger|Taufe;Ramadan|Fasten|Zuckerfest;Muttertag|Blumen|Vatertag;Adventskalender|Türchen|Nikolausstiefel;Konfetti|Bunt|Luftschlangen;Torte|Kerzen|Kuchen;Luftballon|Aufblasen|Girlande;Feuerwerk|Knallen|Wunderkerze;Tannenbaum|Schmuck|Adventskranz;Weihnachtsmann|Rentiere|Nikolaus;Osterhase|Eier|Weihnachtsmann;Sekt|Anstoßen|Champagner;Party|Feiern|Disco;Geschenk|Verpackung|Gutschein;Clown|Lustig|Zauberer' },
  { id: 'fantasy', name: 'Märchen & Fantasy', icon: '🐉', words:
    'Drache|Feuer|Dinosaurier;Einhorn|Horn|Pegasus;Vampir|Blut|Werwolf;Hexe|Besen|Zauberer;Zombie|Untot|Mumie;Geist|Spuk|Gespenst;Meerjungfrau|Fischschwanz|Nixe;Zwerg|Klein|Kobold;Riese|Groß|Troll;Prinzessin|Krone|Königin;Ritter|Rüstung|Soldat;Schneewittchen|Apfel|Dornröschen;Aschenputtel|Schuh|Rapunzel;Rotkäppchen|Wolf|Hänsel und Gretel;Zauberstab|Magie|Besen;Superheld|Umhang|Bösewicht;Alien|Ufo|Roboter;Pirat|Schatz|Wikinger;Ninja|Schwarz|Samurai;Elfe|Spitze Ohren|Fee;Weihnachtself|Nordpol|Wichtel;Fliegender Teppich|Wunderlampe|Besen;Zeitmaschine|Zukunft|Teleporter;Harry Potter|Zauberschule|Herr der Ringe;Frankenstein|Monster|Zombie;Schatzkarte|Kreuz|Kompass;Kristallkugel|Wahrsagen|Tarotkarten;Werwolf|Vollmond|Vampir;Phönix|Asche|Adler;Burg|Turm|Schloss' },
  { id: 'koerper', name: 'Körper & Gesundheit', icon: '🫀', words:
    'Herz|Schlagen|Lunge;Zahn|Beißen|Zunge;Auge|Sehen|Ohr;Nase|Riechen|Mund;Haare|Kopf|Bart;Knie|Bein|Ellbogen;Bauchnabel|Bauch|Muttermal;Fingernagel|Hand|Zehennagel;Pflaster|Wunde|Verband;Spritze|Impfung|Tablette;Gips|Bruch|Schiene;Schnupfen|Nase|Husten;Muskelkater|Sport|Krampf;Gänsehaut|Kalt|Schüttelfrost;Schluckauf|Hicksen|Niesen;Sommersprossen|Sonne|Muttermal;Tattoo|Tinte|Piercing;Zahnspange|Zähne|Brille;Rollstuhl|Räder|Krücken;Massage|Entspannen|Physiotherapie;Schnarchen|Schlafen|Gähnen;Kater|Alkohol|Kopfschmerzen;Sonnenbrand|Rot|Hitzschlag;Fieber|Thermometer|Erkältung;Skelett|Knochen|Schädel;Gehirn|Denken|Herz;Fingerabdruck|Spur|Unterschrift;Blut|Rot|Schweiß;Lächeln|Glücklich|Lachen;Bizeps|Arm|Bauchmuskeln' }
];
