// Wort-Packs: "Wort|Hinweis für Imposter|ähnliches Wort (Imposter-Wort)"
// Das Mystery-Paket hat keine eigenen Wörter: es mischt zufällig aus allen anderen Packs.
window.IMPOSTER_CATEGORIES = [
  { id: 'mystery', name: 'Mystery-Paket', icon: '🎁', mystery: true, words: '' },
  { id: 'alltag', name: 'Alltag', icon: '⏰', words:
    'Kühlschrank|Kalt|Gefriertruhe;Waschmaschine|Wäsche|Trockner;Staubsauger|Saugen|Besen;Bett|Schlafen|Sofa;Toaster|Brot|Sandwichmaker;Mikrowelle|Aufwärmen|Backofen;Fernseher|Bildschirm|Radio;Spiegel|Reflexion|Fenster;Zahnbürste|Bad|Haarbürste;Kerze|Licht|Lampe;Teppich|Boden|Fußmatte;Kissen|Weich|Decke;Gabel|Besteck|Löffel;Topf|Kochen|Pfanne;Schlüssel|Tür|Schloss;Wecker|Morgens|Uhr;Föhn|Haare|Glätteisen;Regenschirm|Regen|Sonnenschirm;Bügeleisen|Falten|Dampfglätter;Mülleimer|Abfall|Papierkorb;Kaffeemaschine|Bohnen|Wasserkocher;Dusche|Wasser|Badewanne;Handtuch|Abtrocknen|Bademantel;Schere|Schneiden|Messer;Gießkanne|Pflanzen|Sprühflasche;Vorhang|Fenster|Jalousie;Kleiderschrank|Kleidung|Kommode;Klopapier|Toilette|Taschentuch;Fernbedienung|Knöpfe|Controller;Steckdose|Strom|Verlängerungskabel' },
  { id: 'halloween', name: 'Halloween-Chaos', icon: '🎃', words:
    'Kürbis|Orange|Melone;Hexe|Besen|Zauberer;Vampir|Blut|Werwolf;Skelett|Knochen|Mumie;Spinnennetz|Spinne|Fliegengitter;Geisterhaus|Spuk|Schloss;Süßes oder Saures|Klingeln|Sankt Martin;Fledermaus|Nacht|Eule;Zombie|Untot|Geist;Grabstein|Friedhof|Denkmal;Kostüm|Verkleiden|Uniform;Hexenkessel|Zaubertrank|Kochtopf;Kerze|Flamme|Laterne;Mumie|Ägypten|Skelett;Werwolf|Vollmond|Wolf;Gruselfilm|Angst|Thriller;Schwarze Katze|Unglück|Rabe;Sarg|Holz|Kiste;Kürbisschnitzen|Messer|Kerzenziehen;Kunstblut|Rot|Ketchup;Frankenstein|Monster|Zombie;Geisterbahn|Kirmes|Achterbahn;Clown|Gruselig|Pantomime;Totenkopf|Pirat|Schädel;Nebelmaschine|Party|Seifenblasenmaschine;Süßigkeiten|Zucker|Schokolade;Besenstiel|Fliegen|Wischmopp;Kristallkugel|Wahrsagerin|Schneekugel;Fluch|Böse|Zauberspruch;Mitternacht|Zwölf|Sonnenaufgang' },
  { id: 'tiere', name: 'Tiere & Natur', icon: '🦁', words:
    'Hund|Haustier|Wolf;Katze|Schnurren|Tiger;Elefant|Rüssel|Nashorn;Giraffe|Hals|Zebra;Pinguin|Eis|Papagei;Hai|Meer|Delfin;Löwe|König|Tiger;Biene|Honig|Wespe;Schlange|Giftig|Eidechse;Pferd|Reiten|Esel;Kuh|Bauernhof|Schaf;Eule|Nacht|Fledermaus;Krokodil|Zähne|Alligator;Affe|Banane|Gorilla;Hamster|Käfig|Meerschweinchen;Schnecke|Langsam|Schildkröte;Spinne|Netz|Ameise;Känguru|Australien|Koala;Frosch|Teich|Kröte;Adler|Fliegen|Falke;Maus|Käse|Ratte;Bär|Winterschlaf|Panda;Fuchs|Schlau|Wolf;Igel|Stacheln|Stachelschwein;Wal|Riesig|Hai;Huhn|Eier|Ente;Schmetterling|Raupe|Libelle;Kamel|Wüste|Lama;Oktopus|Arme|Qualle;Flamingo|Rosa|Storch;Vulkan|Lava|Berg;Regenbogen|Farben|Polarlicht;Gewitter|Blitz|Sturm;Schnee|Weiß|Hagel;Wüste|Sand|Steppe;Dschungel|Lianen|Wald;Wasserfall|Fallen|Fluss;Mond|Nacht|Sonne;Tornado|Wirbel|Hurrikan;Insel|Meer|Halbinsel;Höhle|Dunkel|Tunnel;Gletscher|Eis|Eisberg;Erdbeben|Wackeln|Tsunami;Nebel|Grau|Wolke;Sonnenuntergang|Abend|Sonnenaufgang;Rose|Dornen|Tulpe;Kaktus|Stacheln|Aloe Vera;Pilz|Wald|Moos;Sternschnuppe|Wunsch|Komet;See|Wasser|Teich;Strand|Muscheln|Küste;Baum|Holz|Busch;Sonnenblume|Gelb|Löwenzahn;Herbst|Blätter|Frühling;Hitzewelle|Heiß|Dürre;Korallenriff|Bunt|Aquarium;Lagerfeuer|Flammen|Kamin;Blitz|Donner|Funke;Eiszapfen|Spitz|Schneeflocke;Meteorit|Einschlag|Asteroid' },
  { id: 'essen', name: 'Essen & Trinken', icon: '🍕', words:
    'Pizza|Italien|Flammkuchen;Döner|Imbiss|Dürüm;Sushi|Japan|Onigiri;Spaghetti|Nudeln|Lasagne;Pommes|Frittiert|Kroketten;Burger|Fast Food|Sandwich;Brezel|Bäckerei|Croissant;Schnitzel|Paniert|Cordon bleu;Kaffee|Morgens|Tee;Bier|Oktoberfest|Wein;Schokolade|Süß|Bonbon;Eis|Sommer|Frozen Joghurt;Kartoffelsalat|Grillparty|Nudelsalat;Currywurst|Ruhrpott|Bratwurst;Maultaschen|Schwaben|Ravioli;Spätzle|Schwaben|Nudeln;Pfannkuchen|Pfanne|Waffel;Banane|Gelb|Mango;Erdbeere|Rot|Himbeere;Popcorn|Kino|Chips;Honig|Biene|Marmelade;Käse|Milch|Butter;Ei|Frühstück|Omelett;Suppe|Löffel|Eintopf;Kuchen|Geburtstag|Torte;Tacos|Mexiko|Burrito;Apfelstrudel|Österreich|Apfelkuchen;Cola|Sprudel|Limonade;Müsli|Schüssel|Cornflakes;Knoblauch|Vampir|Zwiebel' },
  { id: 'anime', name: 'Anime', icon: '⚔️', words:
    'Naruto|Ninja|Boruto;One Piece|Piraten|Fairy Tail;Dragon Ball|Kamehameha|Pokémon;Pokémon|Pikachu|Digimon;Sailor Moon|Mond|Pretty Cure;Attack on Titan|Riesen|Demon Slayer;Demon Slayer|Dämonen|Jujutsu Kaisen;Death Note|Notizbuch|Detektiv Conan;Detektiv Conan|Kind|Sherlock Holmes;Studio Ghibli|Totoro|Disney;Chihiros Reise|Badehaus|Prinzessin Mononoke;Manga|Comic|Webtoon;Cosplay|Verkleiden|Kostüm;Samurai|Schwert|Ninja;Katana|Schwert|Dolch;Ramen|Suppe|Udon;Tokio|Japan|Osaka;Mecha|Roboter|Transformer;Shinigami|Tod|Geist;Kawaii|Süß|Niedlich;Goku|Saiyajin|Vegeta;Pikachu|Gelb|Evoli;Ruffy|Strohhut|Zorro;Sushi|Fisch|Onigiri;Otaku|Fan|Gamer;Heidi|Alm|Pippi Langstrumpf;Biene Maja|Biene|Willi;Captain Tsubasa|Fußball|Kicker;Hello Kitty|Katze|My Melody;Anime-Augen|Groß|Kulleraugen' },
  { id: 'promis', name: 'Berühmte Persönlichkeiten', icon: '🌟', words:
    'Albert Einstein|Physik|Isaac Newton;Angela Merkel|Kanzlerin|Olaf Scholz;Michael Jackson|Moonwalk|Elvis Presley;Taylor Swift|Popstar|Beyoncé;Cristiano Ronaldo|Fußball|Lionel Messi;Elon Musk|Tesla|Jeff Bezos;Barack Obama|Präsident|Joe Biden;Helene Fischer|Schlager|Andrea Berg;Arnold Schwarzenegger|Terminator|Sylvester Stallone;Mozart|Komponist|Beethoven;Leonardo da Vinci|Mona Lisa|Michelangelo;Marilyn Monroe|Blond|Audrey Hepburn;Queen Elizabeth|Krone|King Charles;Steve Jobs|Apple|Bill Gates;Dieter Bohlen|DSDS|Thomas Gottschalk;Michael Schumacher|Formel 1|Sebastian Vettel;Heidi Klum|Model|Claudia Schiffer;Napoleon|Feldherr|Julius Cäsar;Kim Kardashian|Reality-TV|Paris Hilton;Mr. Bean|Lustig|Charlie Chaplin;Johnny Depp|Pirat|Orlando Bloom;Lady Gaga|Schrill|Madonna;Usain Bolt|Schnell|Carl Lewis;Shakira|Hüften|Jennifer Lopez;Rihanna|Sängerin|Beyoncé;Til Schweiger|Tatort|Matthias Schweighöfer;Stefan Raab|TV Total|Oliver Pocher;Boris Becker|Tennis|Roger Federer;Jürgen Klopp|Trainer|Pep Guardiola;Eminem|Rapper|Snoop Dogg' },
  { id: 'fantasy', name: 'Fantasie', icon: '🐉', words:
    'Drache|Feuer|Dinosaurier;Einhorn|Horn|Pegasus;Vampir|Blut|Werwolf;Hexe|Besen|Zauberer;Zombie|Untot|Mumie;Geist|Spuk|Gespenst;Meerjungfrau|Fischschwanz|Nixe;Zwerg|Klein|Kobold;Riese|Groß|Troll;Prinzessin|Krone|Königin;Ritter|Rüstung|Soldat;Schneewittchen|Apfel|Dornröschen;Aschenputtel|Schuh|Rapunzel;Rotkäppchen|Wolf|Hänsel und Gretel;Zauberstab|Magie|Besen;Superheld|Umhang|Bösewicht;Alien|Ufo|Roboter;Pirat|Schatz|Wikinger;Ninja|Schwarz|Samurai;Elfe|Spitze Ohren|Fee;Weihnachtself|Nordpol|Wichtel;Fliegender Teppich|Wunderlampe|Besen;Zeitmaschine|Zukunft|Teleporter;Harry Potter|Zauberschule|Herr der Ringe;Frankenstein|Monster|Zombie;Schatzkarte|Kreuz|Kompass;Kristallkugel|Wahrsagen|Tarotkarten;Werwolf|Vollmond|Vampir;Phönix|Asche|Adler;Burg|Turm|Schloss' },
  { id: 'figuren', name: 'Figuren', icon: '🧙', words:
    'Harry Potter|Zauberer|Hermine Granger;Sherlock Holmes|Detektiv|Hercule Poirot;Spider-Man|Netz|Batman;Batman|Fledermaus|Superman;Mickey Mouse|Disney|Donald Duck;SpongeBob|Ananas|Patrick Star;Shrek|Oger|Fiona;Super Mario|Klempner|Luigi;Pumuckl|Kobold|Rumpelstilzchen;Darth Vader|Dunkle Seite|Lord Voldemort;Homer Simpson|Donut|Peter Griffin;Elsa|Eis|Anna;Pinocchio|Lange Nase|Pippi Langstrumpf;Gandalf|Zauberer|Dumbledore;Jack Sparrow|Pirat|Captain Hook;James Bond|Agent|Ethan Hunt;Asterix|Gallier|Obelix;Garfield|Lasagne|Tom;Winnie Puuh|Honig|Paddington;Yoda|Grün|Gollum;Sonic|Schnell|Mario;Shaun das Schaf|Wolle|Wallace;Dracula|Blut|Nosferatu;Hulk|Grün|Thor;Iron Man|Rüstung|Captain America;Lara Croft|Grabräuberin|Indiana Jones;Bob der Baumeister|Bauen|Feuerwehrmann Sam;Die Maus|Sendung|Käpt’n Blaubär;Sandmännchen|Schlafen|Zahnfee;Schlumpf|Blau|Zwerg' },
  { id: 'film', name: 'Film & Fernsehen', icon: '🎬', words:
    'Titanic|Eisberg|Pearl Harbor;Star Wars|Lichtschwert|Star Trek;Harry Potter|Hogwarts|Herr der Ringe;Der König der Löwen|Simba|Das Dschungelbuch;Tatort|Sonntag|Polizeiruf 110;Netflix|Streaming|Disney+;Game of Thrones|Drachen|Vikings;Breaking Bad|Chemielehrer|Narcos;Friends|Café|How I Met Your Mother;Die Simpsons|Gelb|Family Guy;Jurassic Park|Dinosaurier|King Kong;Fluch der Karibik|Piraten|Hook;Avatar|Blau|Dune;Matrix|Rote Pille|Inception;Squid Game|Spiele|Hunger Games;Big Brother|Container|Dschungelcamp;Wer wird Millionär|Quiz|Gefragt Gejagt;Germany’s Next Topmodel|Laufsteg|DSDS;James Bond|007|Mission Impossible;Toy Story|Spielzeug|Cars;Findet Nemo|Fisch|Arielle;Frozen|Eis|Rapunzel;Stranger Things|80er|Dark;Kino|Leinwand|Theater;Popcorn|Snack|Nachos;Oscar|Preis|Golden Globe;Sitcom|Lachen|Soap;Horrorfilm|Angst|Thriller;Zeichentrick|Animation|Puppentrick;Rotkäppchen|Märchen|Schneewittchen' },
  { id: 'fussball', name: 'Fußball', icon: '⚽', words:
    'Tor|Netz|Pfosten;Elfmeter|Punkt|Freistoß;Schiedsrichter|Pfeife|Linienrichter;Abseits|Fahne|Foul;Rote Karte|Platzverweis|Gelbe Karte;Bundesliga|Liga|Champions League;Weltmeisterschaft|Pokal|Europameisterschaft;Bayern München|Rekordmeister|Borussia Dortmund;Torwart|Handschuhe|Libero;Stadion|Fans|Arena;Fallrückzieher|Akrobatik|Kopfball;Trikot|Nummer|Schal;Kapitän|Binde|Trainer;Eckball|Ecke|Einwurf;Fußballschuhe|Stollen|Turnschuhe;Nationalmannschaft|Deutschland|Olympiateam;Bierdusche|Meister|Sektdusche;Videobeweis|Kamera|Torlinientechnik;Hattrick|Drei|Doppelpack;Halbzeit|Pause|Verlängerung;Ultras|Fankurve|Hooligans;Transfer|Wechsel|Ausleihe;Kicker|Tischfußball|Air Hockey;Golden Goal|Verlängerung|Elfmeterschießen;Messi|Argentinien|Ronaldo;Wembley|London|Maracanã;Fußballmanager|Taktik|FIFA;Rasen|Grün|Kunstrasen;Ball|Rund|Medizinball;Panini-Sticker|Sammeln|Pokémon-Karten' },
  { id: 'berufe', name: 'Jobs & Handwerk', icon: '👷', words:
    'Arzt|Krankenhaus|Krankenpfleger;Lehrer|Schule|Erzieher;Polizist|Uniform|Feuerwehrmann;Bäcker|Früh aufstehen|Konditor;Pilot|Flughafen|Flugbegleiter;Koch|Küche|Kellner;Friseur|Schere|Kosmetiker;Mechaniker|Werkstatt|Elektriker;Zahnarzt|Bohren|Arzt;Astronaut|Weltall|Pilot;Anwalt|Gericht|Richter;Bauer|Traktor|Gärtner;Programmierer|Computer|Hacker;Zauberer|Trick|Clown;Maler|Farbe|Künstler;Postbote|Briefe|Paketbote;Tierarzt|Tiere|Arzt;Fotograf|Kamera|Kameramann;Busfahrer|Haltestelle|Taxifahrer;Dachdecker|Höhe|Maurer;Metzger|Fleisch|Koch;Sänger|Bühne|Musiker;Fußballer|Stadion|Trainer;Schauspieler|Film|Sänger;Feuerwehrmann|Brand|Rettungssanitäter;Kassierer|Supermarkt|Verkäufer;CNC-Dreher|Maschine|Fräser;Detektiv|Rätsel|Polizist;Bibliothekar|Bücher|Buchhändler;Müllmann|Tonne|Straßenkehrer' },
  { id: 'koerper', name: 'Körper & Gesundheit', icon: '💪', words:
    'Herz|Schlagen|Lunge;Zahn|Beißen|Zunge;Auge|Sehen|Ohr;Nase|Riechen|Mund;Haare|Kopf|Bart;Knie|Bein|Ellbogen;Bauchnabel|Bauch|Muttermal;Fingernagel|Hand|Zehennagel;Pflaster|Wunde|Verband;Spritze|Impfung|Tablette;Gips|Bruch|Schiene;Schnupfen|Nase|Husten;Muskelkater|Sport|Krampf;Gänsehaut|Kalt|Schüttelfrost;Schluckauf|Hicksen|Niesen;Sommersprossen|Sonne|Muttermal;Tattoo|Tinte|Piercing;Zahnspange|Zähne|Brille;Rollstuhl|Räder|Krücken;Massage|Entspannen|Physiotherapie;Schnarchen|Schlafen|Gähnen;Kater|Alkohol|Kopfschmerzen;Sonnenbrand|Rot|Hitzschlag;Fieber|Thermometer|Erkältung;Skelett|Knochen|Schädel;Gehirn|Denken|Herz;Fingerabdruck|Spur|Unterschrift;Blut|Rot|Schweiß;Lächeln|Glücklich|Lachen;Bizeps|Arm|Bauchmuskeln' },
  { id: 'marken', name: 'Marken', icon: '👟', words:
    'Coca-Cola|Rot|Pepsi;Nike|Swoosh|Adidas;Apple|Apfel|Samsung;McDonald’s|Goldenes M|Burger King;IKEA|Schweden|Möbelhaus;Lego|Steine|Playmobil;Mercedes|Stern|BMW;Volkswagen|Wolfsburg|Opel;Amazon|Paket|eBay;Google|Suchmaschine|Bing;Haribo|Gummibärchen|Katjes;Nutella|Brotaufstrich|Nusspli;Red Bull|Flügel|Monster Energy;Porsche|Sportwagen|Ferrari;Aldi|Discounter|Lidl;Netflix|Serien|Amazon Prime;Ferrero Rocher|Goldpapier|Raffaello;WhatsApp|Chat|Telegram;Instagram|Fotos|TikTok;Milka|Lila Kuh|Ritter Sport;Tempo|Taschentuch|Kleenex;Lufthansa|Kranich|Eurowings;Puma|Raubkatze|Reebok;PlayStation|Sony|Xbox;Starbucks|Kaffee|Tchibo;Duplo|Längste Praline|Kinder Riegel;Nivea|Blaue Dose|Dove;Rolex|Uhr|Omega;Stihl|Motorsäge|Husqvarna;Bosch|Werkzeug|Makita' },
  { id: 'kleidung', name: 'Mode & Kleidung', icon: '👕', words:
    'Jeans|Blau|Jogginghose;Socken|Füße|Strumpfhose;Mütze|Winter|Cap;Krawatte|Anzug|Fliege;Bikini|Strand|Badeanzug;Pyjama|Schlafen|Bademantel;Hoodie|Kapuze|Pullover;Turnschuhe|Sport|Sandalen;Gummistiefel|Regen|Stiefel;Brille|Augen|Sonnenbrille;Handschuhe|Hände|Fäustlinge;Schal|Hals|Halstuch;Kleid|Elegant|Rock;Gürtel|Hose|Hosenträger;Anzug|Hochzeit|Smoking;Unterhose|Drunter|Boxershorts;Lederjacke|Biker|Jeansjacke;Ring|Finger|Armband;Uhr|Handgelenk|Armband;Hut|Kopf|Mütze;Dirndl|Oktoberfest|Lederhose;Regenjacke|Wasserdicht|Windjacke;Hausschuhe|Zuhause|Socken;Rucksack|Schule|Handtasche;Perücke|Haare|Hut;Uniform|Beruf|Arbeitskleidung;Schürze|Kochen|Kittel;Flip-Flops|Sommer|Sandalen;Badehose|Schwimmen|Shorts;Kostüm|Fasching|Verkleidung' },
  { id: 'musik', name: 'Musik', icon: '🎤', words:
    'Gitarre|Saiten|Bass;Klavier|Tasten|Keyboard;Schlagzeug|Trommeln|Cajón;Geige|Bogen|Cello;Trompete|Blasen|Posaune;Flöte|Pusten|Klarinette;Mikrofon|Singen|Lautsprecher;Konzert|Bühne|Festival;Karaoke|Singen|Konzert;DJ|Platten|Produzent;Rap|Reime|Hip-Hop;Oper|Klassisch|Musical;Schlager|Mallorca|Volksmusik;Rock|Laut|Metal;Chor|Gruppe|Band;Kopfhörer|Ohren|Lautsprecher;Mundharmonika|Klein|Akkordeon;Harfe|Engel|Lyra;Ukulele|Hawaii|Gitarre;Saxophon|Jazz|Klarinette;Dudelsack|Schottland|Akkordeon;Taktstock|Dirigent|Metronom;Plattenspieler|Vinyl|Kassette;Radio|Sender|Podcast;Tanz|Bewegung|Ballett;Nationalhymne|Fußball|Volkslied;Weihnachtslied|Advent|Kinderlied;Triangel|Klingeln|Glockenspiel;Spotify|Streaming|Radio;Eurovision|Wettbewerb|Castingshow' },
  { id: 'erwachsene', name: 'Nur Erwachsene', icon: '🌶️', adult: true, words:
    'Kater|Alkohol|Hangover;Flirten|Bar|Anmachen;Erstes Date|Restaurant|Blind Date;Junggesellenabschied|Party|Polterabend;Strip-Poker|Karten|Flaschendrehen;Flaschendrehen|Kuss|Wahrheit oder Pflicht;Tinder|App|Bumble;One-Night-Stand|Nacht|Affäre;Ex-Freund|Vergangenheit|Schwarm;Kondom|Verhütung|Pille;Dessous|Spitze|Pyjama;Whirlpool|Blubbern|Sauna;Knutschfleck|Hals|Kuss;Walk of Shame|Morgen|Heimweg;Rotlichtviertel|Reeperbahn|Partymeile;Tequila|Salz und Zitrone|Wodka;Bierpong|Becher|Flunkyball;Massage|Öl|Wellness;Liebesbrief|Romantik|Valentinskarte;Handschellen|Polizei|Kabelbinder;Eifersucht|Streit|Neid;Schwiegermutter|Familie|Schwiegervater;Fremdgehen|Betrug|Lüge;Nacktbaden|See|Sauna;Sexy|Heiß|Attraktiv;Schlafzimmer|Bett|Hotelzimmer;Absturz|Party|Filmriss;Verlobungsring|Antrag|Ehering;Kuschelrock|Musik|Schmusesong;Peitsche|Leder|Gürtel' },
  { id: 'schule', name: 'Schule', icon: '🎒', words:
    'Lehrer|Tafel|Professor;Tafel|Kreide|Whiteboard;Hausaufgaben|Zuhause|Klassenarbeit;Pausenhof|Pause|Schulhof;Zeugnis|Noten|Urkunde;Schulranzen|Tragen|Rucksack;Mathe|Rechnen|Physik;Klassenfahrt|Ausflug|Schullandheim;Radiergummi|Wegmachen|Tintenkiller;Spickzettel|Schummeln|Notizzettel;Hausmeister|Schlüssel|Sekretärin;Turnhalle|Sport|Aula;Abitur|Prüfung|Abschluss;Schulbus|Fahren|Linienbus;Federmäppchen|Stifte|Geodreieck;Nachsitzen|Strafe|Nachhilfe;Klassenbuch|Einträge|Hausaufgabenheft;Schultüte|Einschulung|Geschenk;Taschenrechner|Zahlen|Handy;Sitzenbleiben|Wiederholen|Versetzung;Elternabend|Eltern|Elterngespräch;Chemie|Experiment|Biologie;Füller|Tinte|Kugelschreiber;Klassensprecher|Wahl|Schülersprecher;Mensa|Essen|Kantine;Lineal|Messen|Geodreieck;Diktat|Schreiben|Aufsatz;Hitzefrei|Sommer|Ferien;Klassenzimmer|Raum|Hörsaal;Schulglocke|Klingeln|Gong' },
  { id: 'sommer', name: 'Sommer', icon: '🏝️', words:
    'Strand|Sand|Schwimmbad;Sonnencreme|Schutz|Aftersun;Eis am Stiel|Kalt|Softeis;Freibad|Rutsche|Baggersee;Grillen|Würstchen|Lagerfeuer;Sonnenbrille|Augen|Taucherbrille;Flip-Flops|Füße|Sandalen;Luftmatratze|Aufblasen|Schwimmring;Sandburg|Schaufel|Sandkasten;Wassermelone|Kerne|Honigmelone;Festival|Zelt|Konzert;Sommerferien|Frei|Osterferien;Hängematte|Schaukeln|Liegestuhl;Cocktail|Schirmchen|Limonade;Sonnenbrand|Rot|Hitzschlag;Mücke|Stich|Wespe;Ventilator|Wind|Klimaanlage;Beachvolleyball|Netz|Volleyball;Wasserpistole|Spritzen|Wasserbombe;Campingplatz|Wohnwagen|Ferienpark;Strandkorb|Ostsee|Liegestuhl;Surfbrett|Welle|Bodyboard;Gewitter|Blitz|Regenschauer;Biergarten|Bier|Terrasse;Cabrio|Offen|Motorrad;Muschel|Meer|Schnecke;Bikini|Strand|Badeanzug;Tretboot|See|Ruderboot;Sonnenschirm|Schatten|Regenschirm;Mallorca|Insel|Ibiza' },
  { id: 'spiele', name: 'Spiele', icon: '🎮', words:
    'Monopoly|Straßen|Die Siedler von Catan;Schach|Matt|Dame;Uno|Karten|Skip-Bo;Minecraft|Blöcke|Roblox;Fortnite|Battle Royale|Call of Duty;Tetris|Blöcke|Candy Crush;Mensch ärgere dich nicht|Würfel|Ludo;Mario Kart|Rennen|Need for Speed;Poker|Bluffen|Blackjack;Jenga|Turm|Mikado;Activity|Pantomime|Tabu;Memory|Paare|Domino;Sudoku|Zahlen|Kreuzworträtsel;Twister|Verrenkungen|Limbo;Wer bin ich|Stirn|Tabu;Verstecken|Suchen|Fangen;Kniffel|Würfel|Yahtzee;GTA|Gangster|Red Dead Redemption;FIFA|Fußball|eFootball;Pac-Man|Geister|Space Invaders;Escape Room|Rätsel|Krimidinner;Puzzle|Teile|Lego;Bingo|Zahlen|Lotto;Skat|Karten|Doppelkopf;Tic Tac Toe|Kreuze|Vier gewinnt;Flaschendrehen|Wahrheit|Wahrheit oder Pflicht;Darts|Pfeile|Kegeln;Among Us|Imposter|Werwolf;Werwolf|Nacht|Mafia;Playstation|Konsole|Nintendo Switch' },
  { id: 'sport', name: 'Sport', icon: '🏆', words:
    'Fußball|Tor|Handball;Basketball|Korb|Volleyball;Tennis|Schläger|Badminton;Schwimmen|Wasser|Tauchen;Boxen|Handschuhe|Kickboxen;Skifahren|Schnee|Snowboard;Golf|Loch|Minigolf;Radfahren|Pedale|Mountainbike;Joggen|Laufen|Marathon;Yoga|Matte|Pilates;Reiten|Pferd|Pony;Bowling|Kegel|Kegeln;Darts|Pfeile|Bogenschießen;Formel 1|Rennen|Kartfahren;Eishockey|Puck|Eiskunstlauf;Surfen|Welle|Windsurfen;Klettern|Wand|Bouldern;Tischtennis|Platte|Tennis;Schach|Figuren|Dame;Turnen|Reck|Akrobatik;Rudern|Boot|Kanu;Fechten|Degen|Kampfsport;Gewichtheben|Hantel|Bodybuilding;Skateboard|Rollen|Inliner;Angeln|Fisch|Jagen;Billard|Kugeln|Snooker;Ringen|Matte|Judo;Rugby|Ei|American Football' },
  { id: 'technik', name: 'Technologie', icon: '📱', words:
    'Smartphone|Apps|Tablet;Laptop|Tragbar|Computer;WLAN|Internet|Bluetooth;Künstliche Intelligenz|ChatGPT|Roboter;Drohne|Fliegen|Hubschrauber;VR-Brille|Virtuell|3D-Brille;Smartwatch|Handgelenk|Fitnesstracker;Elektroauto|Laden|Hybridauto;Akku|Laden|Powerbank;Ladekabel|USB|Netzteil;Kopfhörer|Musik|Lautsprecher;Spielkonsole|Zocken|PC;Selfie|Kamera|Foto;Emoji|Smiley|GIF;Passwort|Geheim|PIN;Cloud|Speicher|USB-Stick;Bildschirm|Anzeige|Beamer;Tastatur|Tippen|Maus;Router|Internet|Modem;Smart Home|Steuern|Alexa;Alexa|Sprachassistent|Siri;3D-Drucker|Drucken|Laserschneider;Roboterstaubsauger|Saugen|Rasenmähroboter;Bluetooth|Kabellos|NFC;QR-Code|Scannen|Barcode;Influencer|Follower|YouTuber;Streaming|Live|Podcast;Virus|Computer|Trojaner;Satellit|Weltall|Rakete;Solarzelle|Sonne|Windrad' },
  { id: 'fahrzeuge', name: 'Transport', icon: '🚗', words:
    'Auto|Straße|Motorrad;Fahrrad|Pedale|Roller;Flugzeug|Fliegen|Hubschrauber;Zug|Schienen|Straßenbahn;Schiff|Meer|Boot;Bus|Haltestelle|Reisebus;Traktor|Feld|Mähdrescher;Rakete|Weltall|Space Shuttle;U-Boot|Unterwasser|Schiff;Feuerwehrauto|Leiter|Krankenwagen;Taxi|Gelb|Uber;Lkw|Ladung|Transporter;Skateboard|Rollen|Longboard;Heißluftballon|Schweben|Zeppelin;Polizeiauto|Blaulicht|Krankenwagen;Gabelstapler|Lager|Hubwagen;Bagger|Baustelle|Radlader;Kutsche|Pferde|Schlitten;Wohnmobil|Urlaub|Wohnwagen;Jetski|Wasser|Motorboot;E-Scooter|Elektrisch|Segway;Seilbahn|Berg|Sessellift;Panzer|Militär|Jeep;Formel-1-Wagen|Rennstrecke|Kart;Monstertruck|Riesenreifen|Pick-up;Segelboot|Wind|Kanu;Müllauto|Tonnen|Kehrmaschine;Rikscha|Asien|Tuk-Tuk;Achterbahn|Kirmes|Geisterbahn;Fallschirm|Springen|Gleitschirm' },
  { id: 'welt', name: 'Welt & Orte', icon: '🌍', words:
    'Italien|Stiefel|Spanien;Japan|Sushi|China;Frankreich|Eiffelturm|Belgien;USA|Freiheitsstatue|Kanada;Ägypten|Pyramiden|Marokko;Australien|Kängurus|Neuseeland;Brasilien|Samba|Argentinien;Russland|Groß|Ukraine;Mexiko|Sombrero|Spanien;Schweiz|Berge|Österreich;Griechenland|Inseln|Türkei;Indien|Curry|Pakistan;Paris|Liebe|London;Berlin|Hauptstadt|Hamburg;New York|Wolkenkratzer|Chicago;Rom|Kolosseum|Athen;Venedig|Gondeln|Amsterdam;Mallorca|Party|Ibiza;London|Big Ben|Dublin;Dubai|Wüste|Katar;Las Vegas|Casino|Monaco;Hawaii|Vulkan|Bali;Norwegen|Fjorde|Schweden;Island|Geysire|Grönland;Thailand|Tempel|Vietnam;Holland|Tulpen|Dänemark;München|Oktoberfest|Stuttgart;Stuttgart|Autos|Karlsruhe;Hollywood|Film|Beverly Hills;Antarktis|Eis|Arktis;Strand|Sand|Schwimmbad;Krankenhaus|Kranke|Arztpraxis;Schule|Lernen|Universität;Kino|Film|Theater;Flughafen|Reisen|Bahnhof;Supermarkt|Einkaufen|Kiosk;Zoo|Tiere|Bauernhof;Friedhof|Ruhe|Kirche;Gefängnis|Zelle|Polizeiwache;Disco|Tanzen|Bar;Bibliothek|Bücher|Buchladen;Fitnessstudio|Hanteln|Sporthalle;Freizeitpark|Achterbahn|Jahrmarkt;Kirche|Glocken|Moschee;Bäckerei|Brötchen|Café;Tankstelle|Benzin|Autowaschanlage;Campingplatz|Zelt|Wohnmobil;Restaurant|Speisekarte|Imbiss;Museum|Ausstellung|Galerie;Hotel|Übernachten|Jugendherberge;U-Bahn|Untergrund|Straßenbahn;Spielplatz|Rutsche|Kindergarten;Bank|Geld|Post;Weltall|Sterne|Mond;Schloss|König|Burg;Wald|Bäume|Park;Baustelle|Kran|Werkstatt;Sauna|Heiß|Dampfbad;Kreuzfahrtschiff|Meer|Fähre;Stadion|Fans|Arena' },
  { id: 'feste', name: 'Feste & Feiern', icon: '🎉', words:
    'Weihnachten|Geschenke|Nikolaus;Ostern|Eier|Pfingsten;Silvester|Feuerwerk|Neujahr;Geburtstag|Kerzen|Jubiläum;Hochzeit|Ringe|Verlobung;Halloween|Kürbis|Fasching;Fasching|Kostüm|Halloween;Oktoberfest|Bier|Weinfest;Junggesellenabschied|Party|Polterabend;Taufe|Baby|Kommunion;Abiball|Schule|Abschlussfeier;Weihnachtsmarkt|Glühwein|Jahrmarkt;Valentinstag|Liebe|Muttertag;Grillparty|Garten|Gartenfest;Einweihungsparty|Neue Wohnung|Richtfest;Babyparty|Schwanger|Taufe;Ramadan|Fasten|Zuckerfest;Muttertag|Blumen|Vatertag;Adventskalender|Türchen|Nikolausstiefel;Konfetti|Bunt|Luftschlangen;Torte|Kerzen|Kuchen;Luftballon|Aufblasen|Girlande;Feuerwerk|Knallen|Wunderkerze;Tannenbaum|Schmuck|Adventskranz;Weihnachtsmann|Rentiere|Nikolaus;Osterhase|Eier|Weihnachtsmann;Sekt|Anstoßen|Champagner;Party|Feiern|Disco;Geschenk|Verpackung|Gutschein;Clown|Lustig|Zauberer' },
  { id: 'freizeit', name: 'Freizeit & Hobbys', icon: '🎳', words:
    'Videospiele|Konsole|Brettspiele;Angeln|Geduld|Jagen;Kochen|Rezept|Backen;Lesen|Buch|Hörbuch;Zelten|Natur|Glamping;Grillen|Kohle|Kochen;Malen|Pinsel|Zeichnen;Tanzen|Musik|Ballett;Gärtnern|Erde|Rasenmähen;Fotografieren|Bilder|Filmen;Wandern|Berge|Spazieren;Puzzle|Teile|Lego;Stricken|Wolle|Häkeln;Shoppen|Einkaufen|Flohmarkt;Netflix|Serien|Kino;Poker|Karten|Roulette;Sauna|Schwitzen|Whirlpool;Escape Room|Rätsel|Krimidinner;Bowling|Kugel|Kegeln;Picknick|Decke|Grillen;Karaoke|Singen|Tanzen;Zaubern|Tricks|Jonglieren;Tauchen|Unterwasser|Schnorcheln;Fallschirmspringen|Flugzeug|Bungee;Modellbau|Kleben|Lego;Sammeln|Briefmarken|Münzen;Meditieren|Ruhe|Yoga;Festival|Zelte|Konzert;Kreuzworträtsel|Zeitung|Sudoku;Instagram|Fotos|TikTok' },
  { id: 'werkstatt', name: 'Werkstatt', icon: '🔧', words:
    'Hammer|Nagel|Schlägel;Schraubenzieher|Schraube|Akkuschrauber;Bohrmaschine|Loch|Fräse;Säge|Holz|Flex;Zange|Greifen|Schraubstock;Drehbank|Spindel|Fräsmaschine;Schweißgerät|Funken|Lötkolben;Messschieber|Messen|Mikrometer;Wasserwaage|Gerade|Zollstock;Schraubstock|Einspannen|Zwinge;Akku|Laden|Batterie;Kabel|Strom|Stecker;Roboter|Automatisch|Drohne;Smartphone|Apps|Tablet;Laptop|Tastatur|Computer;Drucker|Papier|Kopierer;WLAN|Internet|Bluetooth;3D-Drucker|Filament|Laser;Kompressor|Luft|Pumpe;Schleifpapier|Rau|Feile;Gewinde|Schraube|Mutter;Werkbank|Arbeitsfläche|Tisch;Leiter|Hoch|Gerüst;Taschenlampe|Licht|Stirnlampe;Kühlschmierstoff|Emulsion|Öl;Spannfutter|Backen|Spannzange;Lupe|Vergrößern|Mikroskop;Klebeband|Kleben|Sekundenkleber;Magnet|Anziehen|Kompass;Solaranlage|Sonne|Windrad' },
];
