plugins { id 'com.android.application' }
android {
    namespace 'de.sfritz.wischweg'
    compileSdk 34
    defaultConfig {
        applicationId 'de.sfritz.wischweg'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
    sourceSets { main { assets.srcDirs = ['../../game'] } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
